apiVersion: v1
kind: Service
metadata:
    name: "testaks-c1ab"
    labels:
        app: "testaks-c1ab"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "testaks-c1ab"